main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('shop.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('verify-email/<uuid:token>/', views.verify_email, name='verify_email'),
    path('', include('Waikiki.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.registerView, name='register'),
    path('login/', views.authloginView, name='login'),
    path('logout/', views.authLogoutView, name='logout'),
    path('user_list/', views.user_list_view, name='user_list'),
    path('verify-email/<uuid:token>/', views.verify_email, name='verify_email'),
]

templates/footer.html
<footer style="background-color:#1e1e1e; padding:20px 40px; text-align:center; margin-top:40px; box-shadow:0 -4px 10px rgba(0,0,0,0.5);">
   <p style="margin:0;">&copy; 2025 CineBoard. Все права защищены.</p>
   <p style="margin:5px 0 0 0;">Сделано с ❤️ в стиле тёмной темы</p>
</footer>

templates/header.html
<!-- Header -->
<header style="background-color:#1e1e1e; padding:20px 40px; box-shadow:0 4px 10px rgba(0,0,0,0.5); display:flex; justify-content:space-between; align-items:center;">
   <h1 style="margin:0; font-size:24px; color:#ff3c00;">GEEKS 58-1</h1>
   <nav>
       <a href="{% url 'book_list' %}" style="color:#f5f5f5; margin-right:20px; font-weight:bold;">Главная</a>
       <a href="{% url 'all_things' %}" style="color:#f5f5f5; margin-right:20px; font-weight:bold;">Хэштеги</a>
       <a href="#" style="color:#f5f5f5; margin-right:20px; font-weight:bold;">TODO</a>
       <a href="{% url 'users:login' %}" style="color:#f5f5f5; margin-right:20px; font-weight:bold;">Авторизация</a>
       <a href="{% url 'users:register' %}" style="color:#f5f5f5; margin-right:20px; font-weight:bold;">Регистрация</a>
   </nav>
</header>